fun main() {
    val serviceNotes = NoteService()
    val serviceComm = CommentService()
    serviceNotes.add(Notes(1, "привет", "Приветствую всех!",124598, 0))
    serviceComm.add(Comments(1, 1, null, "Hello"), serviceNotes)
    println(serviceNotes.listElem)
    println(serviceComm.listElem)
    serviceComm.add(Comments(1, 1, null, "Hello2"), serviceNotes)
    val commNote = serviceComm.getComment(1)
    println(commNote.listElem)
    val note2 = Notes(0, "привет", "Это моя первая запись!",124598, 0)
    val note3 = Notes(0, "привет", "Я теперь тоже здесь!",124598, 0)
    serviceNotes.add(note2)
    serviceNotes.add(note3)
    serviceComm.add(Comments(1, 2, null, "И я тут!"), serviceNotes)
    serviceComm.add(Comments(1, 2, null, "про меня не забудте!"), serviceNotes)
    println(serviceComm.listElem)
    serviceNotes.delete(note2, serviceComm)
    println(serviceComm.listElem)
}